name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
#    - name: Get all added and modified files
#      uses: jitterbit/get-changed-files@v1
#    - run: |
#        for changed_file in ${{ steps.files.outputs.added_modified }}; do
#        echo "Do something with this ${changed_file}."
#        done
    - name: Lint with flake8
      run: |
        pip install -q wemake-python-styleguide
        wget "https://raw.githubusercontent.com/ebot7/eb7-styleguide/master/settings/setup_ml_githooks.cfg"
        flake8 $pythonfiles --config=setup_ml_githooks.cfg
    - name: Test with pytest
      run: |
        pip install pytest==5.3.5 coverage==4.5.4
        coverage run --source . -m pytest tests --junitxml=reports/test.xml
        coverage xml -o reports/coverage.xml
    - name: codecov
      uses: codecov/codecov-action@v1
      with:
        file: reports/coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
