name: Python application

on: [push,pull_request]

jobs:
  build:

    env:
      PYTHON_FILES

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8.2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
#    - name: get changed files
#      id: getfile
#      run: |
#        if ${{ github.event_name }} = push
#        then
#          echo "::set-output name=files::$(find . -type f -name "*.py" | xargs git diff --name-only --diff-filter=ACMRT ${{ github.sha }}~ ${{ github.sha }}) | awk '{print $1}' | paste -d' ' -s"
#        else
#          echo "::set-output name=files::$(find . -type f -name "*.py" | xargs git diff --name-only --diff-filter=ACMRT ${{ github.base_ref }} ${{ github.head_ref }}) | awk '{print $1}' | paste -d' ' -s"
#    - name: echo output
#      run: |
#        echo ${{ steps.getfile.outputs.files }}
    - name: echo event
      run: |
        if ${{ github.event_name }} = push \
        then \
          echo Registered push \
        else \
          echo Registered pull request \
#    - name: Lint with flake8
#      run: |
#        pip install -q wemake-python-styleguide
#        wget "https://raw.githubusercontent.com/ebot7/eb7-styleguide/master/settings/setup_ml_githooks.cfg"
#        flake8 pgb/ --config=setup_ml_githooks.cfg
#        rm setup_ml_githooks.cfg
#      with:
#        - fail_ci_if_error: true
    - name: Test with pytest
      run: |
        pip install pytest==5.3.5 coverage==4.5.4
        coverage run --source . -m pytest tests --junitxml=reports/test.xml
        coverage xml -o reports/coverage.xml
    - name: codecov
      uses: codecov/codecov-action@v1
      with:
        file: reports/coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
