name: Python application

on: [push,pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: get changed files
      id: getfile
      run: |
        echo "::set-output name=files::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | xargs)"
    - name: echo output
      run: |
        echo ${{ steps.getfile.outputs.files }}
    - name: echo event
      run: |
        echo ${{ github.event.name }}
#    - name: Lint with flake8
#      run: |
#        pip install -q wemake-python-styleguide
#        wget "https://raw.githubusercontent.com/ebot7/eb7-styleguide/master/settings/setup_ml_githooks.cfg"
#        flake8 pgb/ --config=setup_ml_githooks.cfg
#        rm setup_ml_githooks.cfg
#      with:
#        - fail_ci_if_error: true
    - name: Test with pytest
      run: |
        pip install pytest==5.3.5 coverage==4.5.4
        coverage run --source . -m pytest tests --junitxml=reports/test.xml
        coverage xml -o reports/coverage.xml
    - name: codecov
      uses: codecov/codecov-action@v1
      with:
        file: reports/coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
